version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./src/laravel:/var/www/laravel
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - 8008:80
    links:
      - php_fpm
      #- php_websocket

  php_fpm:
    container_name: php_fpm
    build:
      context: ./php
    volumes:
      - ./src/laravel:/var/www/laravel
    ports:
      - 8080:8080
      - 8000:8000
      - 3000:5173
    depends_on:
        - mysql

  php_queue:
    container_name: php_queue
    image: php:8.2-fpm
    volumes:
      - ./src/:/var/www
    working_dir: /var/www/laravel
    command: sh -c "php artisan queue:work"

  #php_websocket:
  #  container_name: php_websocket
  #  image: php:8.2-fpm
  #  volumes:
  #    - ./src/:/var/www
  #  working_dir: /var/www/laravel
  #  command: sh -c "php artisan reverb:start"
  #  ports:
  #    - 8080:8080

  mysql:
    container_name: mysql
    image: mysql:5.7.22
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: laravel 
      MYSQL_PASSWORD: laravel 
      MYSQL_DATABASE: laravel 
