version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./src/laravel:/var/www/laravel
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - 8008:80
    links:
      - php_fpm
      - php_websocket

  php_fpm:
    container_name: php_fpm
    # Вам конечно очень нравится совать Dockerfile в проект, но... в момент билда докер-демон берет все что имеется в директории контекста.
    # А значит держите Dockerfile там где лежит как можно меньше файлов, сборка будет быстрее
    build:
      context: ./php
    volumes:
      - ./src/:/var/www
    links:
        - mysql

  php_queue:
    container_name: php_queue
    image: php:8.2-fpm
    volumes:
      - ./src/:/var/www
    command: "cd /var/www/laravel && php artisan queue:work"

  php_websocket:
    container_name: php_websocket
    image: php:8.2-fpm
    volumes:
      - ./src/:/var/www
    command: "cd /var/www/laravel && php artisan websocket:serve"
    ports:
      - 6000:6000

  mysql:
    container_name: mysql
    image: mysql:5.7.22
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: laravel 
      MYSQL_PASSWORD: laravel 
      MYSQL_DATABASE: laravel 
